name: Ollama UI Build and Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main

      - name: Set VERSION_TAG
        run: |
          VERSION_TAG="${{ steps.tag_version.outputs.new_tag }}"
          if [ -z "$VERSION_TAG" ]; then
            VERSION_TAG="${GITHUB_SHA::7}-$(date +%Y%m%d-%H%M%S)"
          fi
          echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          VERSION_TAG="${VERSION_TAG}"
          COMMIT_TAG="${{ github.sha }}-$(date +%Y%m%d-%H%M%S)"

          echo "Building version: $VERSION_TAG"
          echo "Commit tag: $COMMIT_TAG"

          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/ollama-ui:$VERSION_TAG \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/ollama-ui:$COMMIT_TAG \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/ollama-ui:latest \
            --push .
